get_names = {
        "ACCT": 'Accounting',                   ###
        'AIRS' :'Air Science',
        'ALAR' :'Architecture and Landscape Architecture',
        'AM' : '',
        'AMST': 'American Studies',             ###
        'ANTH' :'Anthropology',                 ###
        'APMA' : 'Applied Mathematics',         ###
        'ARAB' : 'Arabic',                      ###
        'ARAD' : 'Arts Administration',         ###
        'ARAH' : 'History of Art and Architecture',
        'ARCH' : 'Architecture',
        'ARCY' : 'Archaeology',
        'ARH' : 'Architectural History',
        'ARTH' : 'History of Art',
        'ARTR' : 'Arabic in Translation',
        'ARTS' : 'Studio Art',
        'ASL' : 'American Sign Language',
        'ASTR' : 'Astronomy',
        'BIMS' : 'Biomedical Sciences',
        'BIOC' : 'Biochemistry',
        'BIOL' : 'Biology',
        'BIOP' : 'Biophysics',
        'BME':  'Biomedical Engineering',       ###
        'BUS' :  'Business',
        'CASS' :  'College Art Scholars Seminar',
        'CE' : 'Civil Engineering',
        'CELL' :  'Cell Biology',
        'CHE' :  'Chemical Engineering',        ###
        'CHEM' : 'Chemistry',
        'CHIN' :  'Chinese',
        'CHTR' :  'Chinese in Translation',
        'CLAS' :  'Classics',
        'COGS' :  'Cognitive Science',
        'COLA' :  'College Advising Seminar',
        'COMM' :  'Commerce',
        'CONC' :  '',
        'CPE' :  'Computer Engineering',        ###
        'CREO':  'Creole',
        'CS' :  'Computer Science',             ###
        'DANC':  'Dance',
        'DEM' :  'Democracy Initiative',
        'DH' :  'Digital Humanities',
        'DRAM' :  'Drama',
        'DS' :  'Data Science',
        'EALC' :  'East Asian Lang, Lit & Cult',
        'EAST' :  'East Asian Studies',
        'ECE' :  'Electrical & Computer Engr',  ###
        'ECON' : 'Economics',
        'EDHS' :  'Human Services',             ###
        'EDIS' :  'Curriculum, Inst & Spec Ed', ###
        'EDLF':  'Leadership, Foundations Policy',  ###
        'EDNC':  'Education Non-Credit',
        'EGMT' :  'Leadership, Foundations Policy',
        'ELA' :  'Engaging the Liberal Arts',
        'ENCW' :  'Creative Writing',
        'ENGL' :  'English Literature',
        'ENGR' : 'Genre Studies',               ###
        'ENTP' :  'Entrepreneurship',
        'ENWR' :  'English Writing',
        'ESL':  'English as a Second Language',
        'ETP' : 'Enviro Thought & Practice',
        'EURS':  'European Studies',
        'EVAT' :  'Env Sci - Atmospheric Sciences',
        'EVEC' :  'Env Sci - Ecology',
        'EVGE':  'Env Sci - Geosciences',
        'EVHY' :  'Env Sci - Hydrology',
        'EVSC' :  'Environmental Sciences',
        'FREN' :  'French',
        'GBAC' :  'Graduate Business Analytics Comm.',
        'GBUS' :  'Graduate Business',
        'GCCS' :  'Global Commerce in Culture/Soc',
        'GCNL' :  'Clinical Nurse Leader',
        'GCOM' :  'Graduate Commerce',
        'GDS' :  'Global Development Studies',
        'GERM' :  'German',
        'GETR' :  'German in Translation',
        'GHSS' :  'Graduate Humanities & Social Sci',
        'GNUR' :  'Graduate Nursing',
        'GREE' :  'Greek',
        'GSAS' :  '',
        'GSCI' :  '',
        'GSGS' :  'GS-Global Studies',
        'GSMS' :  'GS: Middle East & S Asia',
        'GSSJ' :  'GS-Security and Justice',
        'GSVS' :  'GS-Environments & Sustainabil',
        'HBIO' :  'Human Biology',
        'HEBR' :  'Hebrew',
        'HHE' :  'Health, Humanities & EthicsHHE',
        'HIAF' :  'African History',
        'HIEA' : 'East Asian History',
        'HIEU' :  'European History',
        'HILA' :  'Latin American History',
        'HIME' :  'Middle Eastern History',
        'HIND' :  'Hindi',
        'HISA' :  'South Asian History',
        'HIST' :  'General History',
        'HIUS' :  'United States History',
        'HR' :  'Human Resources',
        'HSCI' :  'College Science Seminar',
        'IMP' :  'Interdisciplinary Thesis',
        'INST' :  'Interdisciplinary Studies',
        'ISBU' :  'IS-Business',
        'ISHU' :  'IS-Humanities',
        'ISIN' :  'IS-Code of Inquiry',
        'ISLS' :  'IS-Liberal Studies Seminar',
        'ISSS':  'IS-Social Sciences',
        'IT' :  'Informational Technology',
        'ITAL' :  'Italian',
        'ITTR' :  'Italian in Translation',
        'JAPN' :  'Japanese',
        'JPTR' :  'Japanese in Translation',
        'KICH' :  "Maya K'iche'",
        'KINE' :  'Kinesiology' ,               ###
        'KLPA' :  'Lifetime Physical Activity',
        'KOR' :  'KoreanKOR',
        'LAR' : 'Landscape Architecture',
        'LASE' :  'Liberal Arts Seminar',
        'LAST' :  'Latin American Studies',
        'LATI' :  'Latin',
        'LAW' :  'Law',
        'LING' :  'Linguistics',
        'LNGS' :  'General Linguistics',
        'LPPA' :  'Public Policy - Analysis',
        'LPPL' :  'Public Policy - Leadership',
        'LPPP':  'Public Policy - Policy',
        'LPPS' :  'Public Policy - Substance',
        'MAE' :  'Mechanical & Aero Engr',      ###
        'MATH':  'Mathematics',
        'MDST' :  'Media Studies',
        'MED' :  'Medicine',
        'MESA' :  'Middle Eastern & South Asian',
        'MICR' :  'Microbiology',
        'MISC' :  'Military Science',
        'MSE' :  'Materials Science & Engr',    ###
        'MSP' :  'Medieval Studies',
        'MUBD' :  'Medieval Studies',
        'MUEN' :  'Music-Ensembles',
        'MUPF' :  'Music-Private Instruction',
        'MUSI' :  'Music',
        'NASC' :  'Naval Science',
        'NCPR' :  'Non-Credit Professional Review',
        'NESC' :  'Neuroscience',
        'NUCO' :  'Nursing Core',
        'NUIP' :  'Nursing Interprofessional',
        'NURS' :  'Nursing',
        'PATH' :  'Pathology',
        'PC' :  'Procurement & Contracts Mgmt',
        'PERS' : 'Persian',
        'PETR' :  'Persian in Translation',
        'PHAR' :  'Pharmacology',
        'PHIL' :  'Philosophy',
        'PHS' :  'Public Health Sciences',
        'PHY' :  'Physiology',
        'PHYS' : 'Physics',
        'PLAC' :  'Planning Application',
        'PLAD' :  'Departmental Seminar',
        'PLAN' :  'Urban & Environ Planning',
        'PLAP' :  'American Politics',
        'PLCP' :  'Comparative Politics',
        'PLIR' :  'International Relations',
        'PLPT' :  'Political Theory',
        'POL' :  'Polish',
        'PORT' :  'Portuguese',
        'POTR' : 'Portuguese in Translation',
        'PPL' :  'Politic Phil, Policy & Law',
        'PSHM' :  'PS-Health Sciences Management',
        'PSLP' :  'PS-Leadership Program',
        'PSPA' :  'PS-Public Administration',
        'PSPM' :  'PS-Project Management',
        'PSPS' :  '',
        'PST' :  'Political & Social Thought',
        'PSYC' :  'Psychology',
        'RELA' :  'African Religions',
        'RELB' :  'Buddhism',
        'RELC' :  'Christianity',
        'RELG' :  'General Religion',
        'RELH' :  'Hinduism',
        'RELI' :  'Islam',
        'RELJ' :  'Judaism',
        'RELS' :  'Religion-Special Topic',
        'RUSS' :  'Russian',
        'RUTR' :  'Russian in Translation',
        'SANS' :  'SanskritSANS',
        'SARC' :  'Architecture School',
        'SAST' :  'South Asian Studies',
        'SATR' :  'South Asian Lit in Trans',
        'SEC' :  'Cyber Security Analysis',
        'SLAV' :  'Slavic',
        'SLTR' :  'Slavic in Translation',
        'SOC' : 'Sociology',
        'SPAN' : 'Spanish',
        'STAT' :  'Statistics',
        'STS' :  'Science, Tech & Society',     ###
        'SWAH' : 'Swahili',
        'SYS' :  'Systems & Information Engr',  ###
        'TURK' : 'Turkish',
        'UD'  : '',
        'UNST' : 'University Studies',
        'URDU' :'Urdu',
        'USEM' : 'University Seminar',
        'WGS': 'Women, Gender & Sexuality'
    }

college_arts_sci = {
    "ACCT": 'Accounting',
    'AM' : '',
    'AMST': 'American Studies',
    'ANTH' :'Anthropology',
    'ARAB' : 'Arabic',
    'ARAD' : 'Arts Administration',
    'ARCY' : 'Archaeology',
    'ARTH' : 'History of Art',
    'ARTR' : 'Arabic in Translation',
    'ARTS' : 'Studio Art',
    'ASL' : 'American Sign Language',
    'ASTR' : 'Astronomy',
    'BIOL' : 'Biology',
    'CASS' :  'College Art Scholars Seminar',
    'CHEM' : 'Chemistry',
    'CHIN' :  'Chinese',
    'CHTR' :  'Chinese in Translation',
    'CLAS' :  'Classics',
    'COGS' :  'Cognitive Science',
    'COLA' :  'College Advising Seminar',
    'CS' :  'Computer Science',
    'CONC' :  '',
    'CREO':  'Creole',
    'DANC':  'Dance',
    'DEM' :  'Democracy Initiative',
    'DH' :  'Digital Humanities',
    'DRAM' :  'Drama',
    'EALC' :  'East Asian Lang, Lit & Cult',
    'EAST' :  'East Asian Studies',
    'ECON' : 'Economics',
    'EGMT' :  'Leadership, Foundations Policy',
    'ELA' :  'Engaging the Liberal Arts',
    'ENCW' :  'Creative Writing',
    'ENGL' :  'English Literature',
    'ENWR' :  'English Writing',
    'ESL':  'English as a Second Language',
    'ETP' : 'Enviro Thought & Practice',
    'EURS':  'European Studies',
    'EVAT' :  'Env Sci - Atmospheric Sciences',
    'EVEC' :  'Env Sci - Ecology',
    'EVGE':  'Env Sci - Geosciences',
    'EVHY' :  'Env Sci - Hydrology',
    'EVSC' :  'Environmental Sciences',
    'FREN' :  'French',
    'GDS' :  'Global Development Studies',
    'GERM' :  'German',
    'GETR' :  'German in Translation',
    'GHSS' :  'Graduate Humanities & Social Sci',
    'GREE' :  'Greek',
    'GSAS' :  '',
    'GSCI' :  '',
    'GSGS' :  'GS-Global Studies',
    'GSMS' :  'GS: Middle East & S Asia',
    'GSSJ' :  'GS-Security and Justice',
    'GSVS' :  'GS-Environments & Sustainabil',
    'HBIO' :  'Human Biology',
    'HEBR' :  'Hebrew',
    'HHE' :  'Health, Humanities & EthicsHHE',
    'HIAF' :  'African History',
    'HIEA' : 'East Asian History',
    'HIEU' :  'European History',
    'HILA' :  'Latin American History',
    'HIME' :  'Middle Eastern History',
    'HIND' :  'Hindi',
    'HISA' :  'South Asian History',
    'HIST' :  'General History',
    'HIUS' :  'United States History',
    'HR' :  'Human Resources',
    'HSCI' :  'College Science Seminar',
    'IT' :  'Informational Technology',
    'ITAL' :  'Italian',
    'ITTR' :  'Italian in Translation',
    'JAPN' :  'Japanese',
    'JPTR' :  'Japanese in Translation',
    'KICH' :  "Maya K'iche'",
    'KLPA' :  'Lifetime Physical Activity',
    'KOR' :  'Korean',
    'LASE' :  'Liberal Arts Seminar',
    'LAST' :  'Latin American Studies',
    'LATI' :  'Latin',
    'LING' :  'Linguistics',
    'LNGS' :  'General Linguistics',
    'MATH':  'Mathematics',
    'MDST' :  'Media Studies',
    'MESA' :  'Middle Eastern & South Asian',
    'MSP' :  'Medieval Studies',
    'MUBD' :  'Medieval Studies',
    'MUEN' :  'Music-Ensembles',
    'MUPF' :  'Music-Private Instruction',
    'MUSI' :  'Music',
    'NCPR' :  'Non-Credit Professional Review',
    'NESC' :  'Neuroscience',
    'PC' :  'Procurement & Contracts Mgmt',
    'PERS' : 'Persian',
    'PETR' :  'Persian in Translation',
    'PHIL' :  'Philosophy',
    'PHS' :  'Public Health Sciences',
    'PHYS' : 'Physics',
    'PLAC' :  'Planning Application',
    'PLAD' :  'Departmental Seminar',
    'PLAN' :  'Urban & Environ Planning',
    'PLAP' :  'American Politics',
    'PLCP' :  'Comparative Politics',
    'PLIR' :  'International Relations',
    'PLPT' :  'Political Theory',
    'POL' :  'Polish',
    'PORT' :  'Portuguese',
    'POTR' : 'Portuguese in Translation',
    'PPL' :  'Politic Phil, Policy & Law',
    'PSHM' :  'PS-Health Sciences Management',
    'PSLP' :  'PS-Leadership Program',
    'PSPA' :  'PS-Public Administration',
    'PSPM' :  'PS-Project Management',
    'PSPS' :  '',
    'PST' :  'Political & Social Thought',
    'PSYC' :  'Psychology',
    'RELA' :  'African Religions',
    'RELB' :  'Buddhism',
    'RELC' :  'Christianity',
    'RELG' :  'General Religion',
    'RELH' :  'Hinduism',
    'RELI' :  'Islam',
    'RELJ' :  'Judaism',
    'RELS' :  'Religion-Special Topic',
    'RUSS' :  'Russian',
    'RUTR' :  'Russian in Translation',
    'SANS' :  'SanskritSANS',
    'SAST' :  'South Asian Studcsies',
    'SATR' :  'South Asian Lit in Trans',
    'SEC' :  'Cyber Security Analysis',
    'SLAV' :  'Slavic',
    'SLTR' :  'Slavic in Translation',
    'SOC' : 'Sociology',
    'SPAN' : 'Spanish',
    'STAT' :  'Statistics',
    'SWAH' : 'Swahili',
    'TURK' : 'Turkish',
    'UD'  : '',
    'URDU' :'Urdu',
    'WGS': 'Women, Gender & Sexuality'
}

edu_hum_dev_school = {
    'EDHS' :  'Human Services',
    'EDIS' :  'Curriculum, Inst & Spec Ed',
    'EDLF':  'Leadership, Foundations Policy',
    'EDNC':  'Education Non-Credit',
    'KINE' :  'Kinesiology'
}

engr_school = {
    'APMA' : 'Applied Mathematics',
    'BME':  'Biomedical Engineering',
    'CE' : 'Civil Engineering',
    'CHE' :  'Chemical Engineering',
    'CPE' :  'Computer Engineering',
    'CS' :  'Computer Science',
    'ECE' :  'Electrical & Computer Engr',
    'ENGR' : 'Genre Studies',
    'MAE' :  'Mechanical & Aero Engr',
    'MSE' :  'Materials Science & Engr',
    'STS' :  'Science, Tech & Society',
    'SYS' :  'Systems & Information Engr'
}

other_schools = {
    'AIRS' :'Air Science',
    'ALAR' :'Architecture and Landscape Architecture',
    'ARAH' : 'History of Art and Architecture',
    'ARCH' : 'Architecture',
    'ARH' : 'Architectural History',
    'BIMS' : 'Biomedical Sciences',
    'BIOC' : 'Biochemistry',
    'BIOP' : 'Biophysics',
    'BUS' :  'Business',
    'CELL' :  'Cell Biology',
    'COMM' :  'Commerce',
    'DS' :  'Data Science',
    'ENTP' :  'Entrepreneurship',
    'GBAC' :  'Graduate Business Analytics Comm.',
    'GBUS' :  'Graduate Business',
    'GCCS' :  'Global Commerce in Culture/Soc',
    'GCNL' :  'Clinical Nurse Leader',
    'GCOM' :  'Graduate Commerce',
    'GNUR' :  'Graduate Nursing',
    'IMP' :  'Interdisciplinary Thesis',
    'INST' :  'Interdisciplinary Studies',
    'ISBU' :  'IS-Business',
    'ISHU' :  'IS-Humanities',
    'ISIN' :  'IS-Code of Inquiry',
    'ISLS' :  'IS-Liberal Studies Seminar',
    'ISSS':  'IS-Social Sciences',
    'LAW' :  'Law',
    'LAR' : 'Landscape Architecture',
    'LPPA' :  'Public Policy - Analysis',
    'LPPL' :  'Public Policy - Leadership',
    'LPPP':  'Public Policy - Policy',
    'LPPS' :  'Public Policy - Substance',
    'MED' :  'Medicine',
    'MICR' :  'Microbiology',
    'MISC' :  'Military Science',
    'NASC' :  'Naval Science',
    'NUCO' :  'Nursing Core',
    'NUIP' :  'Nursing Interprofessional',
    'NURS' :  'Nursing',
    'PATH' :  'Pathology',
    'PHAR' :  'Pharmacology',
    'PHY' :  'Physiology',
    'SARC' :  'Architecture School',
    'USEM' : 'University Seminar',
    'UNST' : 'University Studies'
}