# Generated by Django 3.2.15 on 2022-10-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewLousList', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
