# Generated by Django 4.1.2 on 2022-10-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewLousList', '0003_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
