# Generated by Django 4.1.2 on 2022-10-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewLousList', '0004_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=200)),
                ('instructor_email', models.CharField(max_length=200)),
                ('course_number', models.IntegerField(default=0)),
                ('semester_code', models.IntegerField(default=0)),
                ('course_section', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('catalog_number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('component', models.CharField(max_length=200)),
                ('class_capacity', models.IntegerField(default=0)),
                ('wait_list', models.IntegerField(default=0)),
                ('wait_cap', models.IntegerField(default=0)),
                ('enrollment_total', models.IntegerField(default=0)),
                ('enrollment_available', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=200)),
                ('meeting_days', models.CharField(max_length=200)),
                ('meeting_start_time', models.CharField(max_length=200)),
                ('meeting_end_time', models.CharField(max_length=200)),
                ('meeting_facility_description', models.CharField(max_length=200)),
            ],
        ),
    ]
