# Generated by Django 4.1.2 on 2022-10-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewLousList', '0005_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='meeting_end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_facility_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_start_time',
        ),
    ]
