# Generated by Django 4.1.2 on 2022-11-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NewLousList", "0010_userinfo"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="username_slug",),
    ]
