# Generated by Django 4.1.2 on 2022-11-11 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("NewLousList", "0011_remove_userinfo_username_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="receiver",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="sender",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
