# Generated by Django 4.1.2 on 2022-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NewLousList", "0015_alter_course_options_alter_userinfo_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="class_list",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="class_list",
                to="NewLousList.course",
            ),
        ),
    ]
