# Generated by Django 4.1.2 on 2022-11-13 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("NewLousList", "0017_alter_shoppingcart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="class_list",
            field=models.ManyToManyField(
                blank=True, related_name="class_list", to="NewLousList.course"
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
