# Generated by Django 4.1.2 on 2022-11-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewLousList', '0020_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meetings',
            field=models.JSONField(default=dict),
        ),
    ]
