# Generated by Django 4.1.2 on 2022-12-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewLousList', '0021_alter_course_meetings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
