# Generated by Django 4.1.2 on 2022-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewLousList', '0022_alter_course_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=10)),
                ('review_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
