# Generated by Django 4.1.2 on 2022-12-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NewLousList", "0023_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="first_name",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="last_name",
            field=models.CharField(default=" ", max_length=50),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="major",
            field=models.CharField(default=" ", max_length=50),
        ),
    ]
